In [47]:
import pandas as pd
data = pd.read_csv('/content/pca.csv')
data.head()

A    B   C   D    E     F      G   H  I
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [48]:
# prompt: now i wanna split data horizontally A to H coumns in X and I column in Y

X = data[['A','B','C','D','E','F','G','H']]
Y = data['I']


In [49]:
# prompt: now i have to normalize the X using min max scaler

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X = scaler.fit_transform(X)


In [50]:
# prompt: split the data into train and test data using sklearn

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.1, random_state=12)
X_train


array([[0.125     , 0.        , 0.8125    , 0.82857143, 0.        ,
        0.16666667, 0.08675153, 0.34482759],
       [1.        , 1.        , 0.75      , 0.        , 0.        ,
        0.        , 0.23809524, 0.37931034],
       [0.        , 0.53061224, 0.        , 1.        , 1.        ,
        1.        , 1.        , 0.4137931 ],
       [0.125     , 0.04081633, 0.8125    , 0.65714286, 0.55952381,
        0.24242424, 0.        , 0.        ]])

In [51]:
# prompt: import SVC and fit train data

from sklearn.svm import SVC

svc_classifier = SVC()
svc_classifier.fit(X_train, y_train)
svc_classifier.score(X_test, y_test)


1.0

In [52]:
X.shape

(5, 8)

In [53]:
from sklearn.decomposition import PCA
pca = PCA(0.90)
xpca = pca.fit_transform(X)
xpca.shape

(5, 3)

what does the PCA do ??

It reduce the dimension of data and only consider important features .. it is useful to save computation time

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(xpca,Y,test_size=0.2,random_state=0)


In [55]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)

SVC()

In [56]:
model.score(X_test, y_test)

1.0

In [57]:
X.shape

(5, 8)

In [58]:
X

array([[0.75      , 0.64285714, 1.        , 1.        , 0.        ,
        0.52020202, 0.21687883, 1.        ],
       [0.125     , 0.        , 0.8125    , 0.82857143, 0.        ,
        0.16666667, 0.08675153, 0.34482759],
       [1.        , 1.        , 0.75      , 0.        , 0.        ,
        0.        , 0.23809524, 0.37931034],
       [0.125     , 0.04081633, 0.8125    , 0.65714286, 0.55952381,
        0.24242424, 0.        , 0.        ],
       [0.        , 0.53061224, 0.        , 1.        , 1.        ,
        1.        , 1.        , 0.4137931 ]])

In [89]:
X.shape

(5, 8)

In [59]:
pca = PCA(n_components=4)
xpca = pca.fit_transform(X)
xpca.shape

(5, 4)

In [60]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)

SVC()

In [61]:
model.score(X_test, y_test)

1.0

Hypertuniny :- By hypertuning we create a perfect model by finding the perfect combination and value of parameters

In [62]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
table = pd.DataFrame(iris.data,columns=iris.feature_names)
table.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [63]:
table['target'] = iris.target
table.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [64]:
x = table.drop(['target'], axis='columns')
y = iris.target

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [66]:
from sklearn.tree import DecisionTreeClassifier

In [67]:
dt1 = DecisionTreeClassifier(criterion= 'gini', splitter= 'best', max_depth=2)
dt2 = DecisionTreeClassifier(criterion= 'entropy', splitter= 'best', max_depth=5)
dt3 = DecisionTreeClassifier(criterion= 'gini', splitter= 'random', max_depth= 4)
dt4 = DecisionTreeClassifier(criterion= 'entropy', splitter= 'random', max_depth= 6)

In [68]:
dt1.fit(X_train, y_train)
dt2.fit(X_train, y_train)
dt3.fit(X_train, y_train)
dt4.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6, splitter='random')

In [69]:
print('dt1 -> ',dt1.score(X_test, y_test))
print('dt2 -> ',dt2.score(X_test, y_test))
print('dt3 -> ',dt3.score(X_test, y_test))
print('dt4 -> ',dt4.score(X_test, y_test))

dt1 ->  0.9666666666666667
dt2 ->  1.0
dt3 ->  0.9666666666666667
dt4 ->  1.0


Like this we can do hypertuniny manually

Someautomatic way for hypertuning

In [70]:
dt = DecisionTreeClassifier()

In [71]:
from sklearn.model_selection import GridSearchCV

In [72]:
options = {'criterion': ('gini','entropy'),'splitter': ('best','random'),'max_depth' : list(range(1,7)) }

what does the gridsearchCv do ??

It use all possible combination of parameters and give us the best among them

In [73]:
gs = GridSearchCV(dt,options)
gs.fit(X_train, y_train)


GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ('gini', 'entropy'),
                         'max_depth': [1, 2, 3, 4, 5, 6],
                         'splitter': ('best', 'random')})

In [90]:
# gs.cv_results_['params']

In [75]:
gs.best_params_

{'criterion': 'gini', 'max_depth': 2, 'splitter': 'best'}

In [76]:
scores=gs.cv_results_['mean_test_score']
scores

array([0.69166667, 0.65      , 0.94166667, 0.83333333, 0.925     ,
       0.925     , 0.925     , 0.9       , 0.93333333, 0.93333333,
       0.93333333, 0.94166667, 0.69166667, 0.675     , 0.93333333,
       0.725     , 0.93333333, 0.93333333, 0.925     , 0.90833333,
       0.93333333, 0.91666667, 0.93333333, 0.90833333])

In [77]:
import numpy as np
np.argmax(scores)

2

In [78]:
scores[2]

0.9416666666666667

In [79]:
from sklearn.model_selection import RandomizedSearchCV

In [80]:
dt = DecisionTreeClassifier()

In [81]:
options = {'criterion': ('gini','entropy'),'splitter': ('best','random'),'max_depth' : list(range(1,7)) }

what does randomizedsearch CV do ??

It choose the parameters randomly and from them give us the best combo ... it may be type of luck game but it saves the computation time


In [82]:
samples = 5
rs = RandomizedSearchCV(dt, param_distributions=options, n_iter=samples)

In [83]:
rs.fit(X_train, y_train)

RandomizedSearchCV(estimator=DecisionTreeClassifier(), n_iter=5,
                   param_distributions={'criterion': ('gini', 'entropy'),
                                        'max_depth': [1, 2, 3, 4, 5, 6],
                                        'splitter': ('best', 'random')})

In [84]:
rs.cv_results_['params']

[{'splitter': 'best', 'max_depth': 2, 'criterion': 'entropy'},
 {'splitter': 'random', 'max_depth': 6, 'criterion': 'gini'},
 {'splitter': 'best', 'max_depth': 2, 'criterion': 'gini'},
 {'splitter': 'random', 'max_depth': 5, 'criterion': 'gini'},
 {'splitter': 'random', 'max_depth': 4, 'criterion': 'entropy'}]

In [85]:
rs.best_params_

{'splitter': 'best', 'max_depth': 2, 'criterion': 'gini'}

In [86]:
scores = rs.cv_results_['mean_test_score']
scores

array([0.93333333, 0.90833333, 0.94166667, 0.94166667, 0.93333333])

In [87]:
np.argmax(scores)

2

In [88]:
scores[2]

0.9416666666666667